In [2]:
import torch
#自动微分
x=torch.arange(4.0,requires_grad=True)
x.grad  # 默认值是None
y = 3 * torch.dot(x, x)
print(x)
print(y)
y.backward()
x.grad

tensor([0., 1., 2., 3.], requires_grad=True)
tensor(42., grad_fn=<MulBackward0>)


tensor([ 0.,  6., 12., 18.])

In [3]:
# 计算另外一种梯度
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值

x.grad.zero_() # 相当于把计算图给清空了
y = x.sum()    # x1+x2+x3+x4
y.backward()   # 做x1+x2+x3+x4的梯度
x.grad

tensor([1., 1., 1., 1.])

In [ ]:
#分离计算，有时，我们希望将某些计算移动到记录的计算图之外。 例如，假设y是作为x的函数计算的，而z则是作为y和x的函数计算的。 
#想象一下，我们想计算z关于x的梯度，但由于某种原因，我们希望将y视为一个常数， 并且只考虑到x在y被计算后发挥的作用。
#在这里，我们可以分离y来返回一个新变量u，该变量与y具有相同的值， 但丢弃计算图中如何计算y的任何信息。 
#换句话说，梯度不会向后流经u到x。 因此，下面的反向传播函数计算z=u*x关于x的偏导数，同时将u作为常数处理， 
#而不是z=x*x*x关于x的偏导数。
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

In [ ]:
#由于记录了y的计算结果，我们可以随后在y上调用反向传播， 
#得到y=x*x关于的x的导数，即2*x
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x